### ISSUE TITLE
Cannot connect to the balena daemon at unix:///var/run/balena.sock. Is the balena daemon running?

### ISSUE THREAD

**Issue by AnnapoorniS** [balena-os/balena-engine#72] opened 2018-02-04 17:58 UTC
Hi,
Creating the sub issue of [https://github.com/resin-os/balena/issues/55](url)

Tried the below commands and ended up in errors
sudo systemctl enable balena
Failed to execute operation: No such file or directory

sudo systemctl status balena
● balena.service
Loaded: not-found (Reason: No such file or directory)
Active: inactive (dead)

sudo systemctl start balena
Failed to start balena.service: Unit balena.service not found.

Kindly suggest any ways that balena can run continuously as a background service on rebooting the machine.

Thanks

**Comment by AnnapoorniS** [comment] 2018-02-04 18:20
While trying to pull images from a registry getting TLS handshake error:

> 
> failed to retrieve balena-init version: exec: "balena-init": executable file not found in $PATH 
> WARN[1125] Couldn't run auplink before unmount /var/lib/balena/aufs/mnt/dd2b49c5a0c3fe1ea4d7e80a58dbf7f9469c67db130a0ed65211c59ef759d6eb-init: exec: "auplink": executable file not found in $PATH 
> WARN[1125] Couldn't run auplink before unmount /var/lib/balena/aufs/mnt/dd2b49c5a0c3fe1ea4d7e80a58dbf7f9469c67db130a0ed65211c59ef759d6eb: exec: "auplink": executable file not found in $PATH 
> INFO[1125] No non-localhost DNS nameservers are left in resolv.conf. Using default external servers: [nameserver 8.8.8.8 nameserver 8.8.4.4] 
> INFO[1125] IPv6 enabled; Adding default IPv6 external servers: [nameserver 2001:4860:4860::8888 nameserver 2001:4860:4860::8844] 
> WARN[1126] Couldn't run auplink before unmount /var/lib/balena/aufs/mnt/dd2b49c5a0c3fe1ea4d7e80a58dbf7f9469c67db130a0ed65211c59ef759d6eb: exec: "auplink": executable file not found in $PATH
> Getting the error of TLS handshake failure too
> remote error: tls: handshake failure

But those images  gets pulled with docker but fails with balena pull, 

What is the issue specific to balena in pulling the images from the registry.

**Comment by shaunmulligan** [comment] 2018-02-06 11:29
Hey @AnnapoorniS how did you install Balena? did you install from source, the download or did you use the install script `curl -sfL https://balena.io/install.sh | sh` ?

**Comment by AnnapoorniS** [comment] 2018-02-06 14:55
Hi @shaunmulligan 
I used the install script, `curl -sfL https://balena.io/install.sh | sh`

Tried in Ubuntu 16 and RaspberryPi jessie OS

**Comment by maiorfi** [comment] 2018-03-10 14:27
I also tried to copy contrib/init/systemd/* files into /lib/systemd/system dir and enabling service, but:

1) chown fails if current user is not in balena group (maybe install script should add current user to balena group)
2) once started service, balena.socket dependecy complains about being (re)started too quickly

Tried on debian 9.3 running on beaglebone

Thx!

**Comment by cnrmck** [comment] 2018-12-04 01:11
This is how I solved a somewhat similar problem https://github.com/balena-os/balena-engine/issues/55

**Comment by robertgzr** [comment] 2019-01-08 11:55
as pointed out by @cnrmck, this is a duplicate of #55

**Closed by robertgzr** 2019-01-08 11:55 UTC
