### ISSUE TITLE
Getting illegal instruction on arm6 builds when running on rpi zero w

### ISSUE THREAD

**Issue by sokoow** [balena-os/balena-engine#143] opened 2019-02-05 12:44 UTC
Hey, I'm in a catch 22 at the moment - you arm 6 builds are giving 'illegal instruction' on rpi zero w, and cross compiling on that device is not possible due to lack of memory. Any ideas ? :)

**Comment by diogoviannaaraujo** [comment] 2019-02-25 12:56
having the same problem... resin was so promising...

**Comment by sokoow** [comment] 2019-02-25 12:57
I recompiled it on the host directly and it works now, but official builds for pi zero are borked

**Comment by robertgzr** [comment] 2019-07-23 14:23
Probably a duplicate of or very similar to #141

**Closed by robertgzr** 2019-07-23 14:23 UTC
Labels: distribution

**Comment by dogi** [comment] 2019-08-05 07:59
```
strace /usr/local/bin/balena-engine-daemon -H tcp://0.0.0.0:2375 -H unix:///var/run/balena-engine.sock
execve("/usr/local/bin/balena-engine-daemon", ["/usr/local/bin/balena-engine-dae"..., "-H", "tcp://0.0.0.0:2375", "-H", "unix:///var/run/balena-engine.so"...], 0xbea87ca0 /* 21 vars */) = 0
--- SIGILL {si_signo=SIGILL, si_code=ILL_ILLOPC, si_addr=0x5eb54} ---
+++ killed by SIGILL +++
Illegal instruction
```

**Comment by dogi** [comment] 2019-08-05 08:00
this with new raspbian based on debian buster
